### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by XiaoBWang1** [XiaoBWang1/LostGrenadiers#1]
Create a logo that all 3 for the project and upload onto Github.

**Comment by XiaoBWang1** [comment]
Maybe a grenade with the map of the campus covering it. Might have to try generative artificial intelligence due to lack of ideas.

**Comment by ChrisRHolley** [comment]
Just messing around, but maybe something like this?
![Possilble Logo](https://github.com/user-attachments/assets/51cdcaef-7850-4761-8b19-f7269236ee40)
